receivers:
  netflow:
  #   - scheme: netflow
  #     port: 2055
  #     sockets: 16
  #     workers: 32
  netflow/sflow:
  #   - scheme: sflow
  #     port: 6343
  #     sockets: 16
  #     workers: 32

processors:
  batch:
    send_batch_size: 2000
    timeout: 30s
  geoip:
    context: record
    attributes: [source.address, destination.address]
    providers:
      maxmind:
        database_path: /maxmind-db

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "mrx0kVmkQ0hqCOBH8heJmE"
      "x-honeycomb-dataset": "netflow"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [netflow, netflow/sflow]
      processors: [geoip, batch]
      exporters: [debug, otlp]
  telemetry:
    logs:
      level: debug
