receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  debug:
  file/rotation_with_default_settings:
    path: /file-exporter/dump.json
    rotation:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file]