version: '3'

services:
  collector:
    image: local/collector-otlp-dump
    volumes:
      - ./config.yaml:/config.yaml
      - ./file-exporter:/file-exporter
    ports:
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
