version: '3'

services:
  collector:
    image: local/collector-netmon
    volumes:
      - ./config.yaml:/config.yaml
      - ./Geolite2-City_2025_0228/Geolite2-City.mmdb:/maxmind-db
    ports:
      - "13133:13133"
      - "6343:6343/udp"
      - "2055:2055/udp"
    environment:
      - OTEL_SERVICE_NAME=netmon
