version: '3'

services:
  collector:
    image: local/collector-netmon
    volumes:
      - ./config.yaml:/config.yaml
      - ./GeoLite2-City_20250228/GeoLite2-City.mmdb:/maxmind-db
    ports:
      - "13133:13133"
      - "6343:6343/udp"
      - "2055:2055/udp"
    environment:
      - OTEL_SERVICE_NAME=geoip-src
      - OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team={HNY_API_KEY}"
